# Generated by Django 3.2.6 on 2021-10-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210911_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.article')),
            ],
            bases=('blog.article',),
        ),
    ]
