# Generated by Django 3.2.6 on 2021-10-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtube_youtube_embed_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='youtube_embed_url',
            field=models.URLField(default='https://www.youtube.com/embed/WGlGgTQf8FE', max_length=300),
            preserve_default=False,
        ),
    ]
