# Generated by Django 3.2.6 on 2021-10-27 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0003_youtube_youtube_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(max_length=300)),
                ('youtube_embed_html', models.TextField()),
                ('youtube_embed_url', models.URLField(max_length=300)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
